project:
  type: website
  output-dir: docs
  pre-render: ./update-site.sh
  render:
    - "*.qmd"
    - "guides/*.qmd"
    - "!slides/"
  resources:
    - slides/**
    - "!slides/draft*/**"

website:
  title: "War and State Development"
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - href: syllabus_2026_spring.qmd
        text: Syllabus

format:
  html:
    theme:
      - default
      - wasd.scss
    monofont: 'Source Code Pro'
    linestretch: 1.7
